databases:
  - name: budget
    databaseName: budget_icuq
    user: budget_icuq_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_icuq
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
